@echo off
wzzip -f "Z:\XHP\utilities\XCC_AUD_Writer.zip" "e:\vc\out_aud\release"
wzzip -f "Z:\XHP\utilities\XCC_AV_Player.zip" "e:\vc\xcc\xcc av player\release\" "e:\vc\xcc\data\"
wzzip -f "Z:\XHP\utilities\XCC_Cheat_Reporter.zip" "e:\vc\xcc\xcc cheat reporter\release\" "e:\vc\xcc\data\"
wzzip -f "Z:\XHP\utilities\XCC_DLL_Pack.zip" "c:\w98\system\"
wzzip -f "Z:\XHP\utilities\XCC_IMA_ADPCM_WAV_Writer.zip" "e:\vc\out_ima_adpcm_wav\release"
wzzip -f "Z:\XHP\utilities\XCC_Map_ED.zip" "e:\vc\xcc\xcc map encoder\release\" "e:\vc\xcc\data\"
wzzip -f "Z:\XHP\utilities\XCC_Map_ED.zip" "e:\vc\xcc\xcc map decoder\release\"
wzzip -f "Z:\XHP\utilities\XCC_MIX_Editor.zip" "e:\vc\xcc\xcc mix editor\release\" "e:\vc\xcc\data\"
wzzip -f "Z:\XHP\utilities\XCC_Mixer.zip" "e:\vc\xcc\xcc mixer\release\" "e:\vc\xcc\data\"
wzzip -f "Z:\XHP\utilities\XCC_Mod_CL.zip" "e:\vc\xcc\xcc mod creator\release\" "e:\vc\xcc\data\"
wzzip -f "Z:\XHP\utilities\XCC_Mod_CL.zip" "e:\vc\xcc\xcc mod launcher\release\"
wzzip -f "Z:\XHP\utilities\XCC_Utilities.zip" "e:\vc\xcc\xcc av player\release\" "e:\vc\xcc\data\"
wzzip -f "Z:\XHP\utilities\XCC_Utilities.zip" "e:\vc\xcc\xcc mix editor\release\"
wzzip -f "Z:\XHP\utilities\XCC_Utilities.zip" "e:\vc\xcc\xcc mixer\release\"
wzzip -f "Z:\XHP\utilities\XCC_Utilities.zip" "e:\vc\xcc\xcc tmp editor\release\"
wzzip -f "Z:\XHP\utilities\XIF_Editor.zip" "e:\vc\xif editor\release\"
wzzip -f "Z:\XHP\utilities\XRC.zip" "e:\vc\xcc\xcc ra2 radar customizer\release\" "e:\vc\xcc\data\"
wzzip -f "Z:\XHP\utilities\XRMU.zip" "e:\vc\xcc\xcc ra2 map updater\release\" "e:\vc\xcc\data\"
wzzip -f "Z:\XHP\utilities\XSE_CLT.zip" "e:\vc\xcc\xse clt\release\" "e:\vc\xcc\data\"
rem wzzip -f "Z:\XHP\utilities\XWIF.zip" "e:\vc\xcc\xcc wol irc filter\release\" "e:\vc\xcc\data\"

