@echo off
c:\utils\upx\upx -q --best "E:\VC\xcc\XCC Map Decoder\Release\XCC Map Decoder.exe" "E:\VC\xcc\XCC Mod Launcher\Release\XCC Mod Launcher.exe" "E:\VC\xcc\XCC WOL IRC Filter\Release\WOL Matching Filter.exe"
copy "e:\vc\xcc\xcc mod launcher\release\xcc mod launcher.exe" "e:\vc\xcc\xcc mod creator\release\*"
copy "e:\vc\xcc\xcc game spy\release\xcc game spy.exe" "e:\vc\xcc\xcc wol irc filter\release\*"
wzzip -f "e:\xhp\utilities\MF.zip" "e:\vc\xcc\xcc ra2 map updater\release\"
wzzip -f "e:\xhp\utilities\MF.zip" "e:\vc\xcc\xcc ra2 radar customizer\release\"
wzzip -f "e:\xhp\utilities\MF.zip" "e:\vc\xcc\xcc wol irc filter\release\"
wzzip -f "e:\xhp\utilities\XCC_AUD_Writer.zip" "e:\vc\out_aud\release"
wzzip -f "e:\xhp\utilities\XCC_AV_Player.zip" "e:\vc\xcc\xcc av player\release\" "e:\vc\xcc\data\"
wzzip -f "e:\xhp\utilities\XCC_Cheat_Reporter.zip" "e:\vc\xcc\xcc cheat reporter\release\" "e:\vc\xcc\data\"
wzzip -f "e:\xhp\utilities\XCC_DLL_Pack.zip" "c:\w98\system\"
wzzip -f "e:\xhp\utilities\XCC_IMA_ADPCM_WAV_Writer.zip" "e:\vc\out_ima_adpcm_wav\release"
wzzip -f "e:\xhp\utilities\XCC_Map_ED.zip" "e:\vc\xcc\xcc map encoder\release\" "e:\vc\xcc\data\"
wzzip -f "e:\xhp\utilities\XCC_Map_ED.zip" "e:\vc\xcc\xcc map decoder\release\"
wzzip -f "e:\xhp\utilities\XCC_MIX_Editor.zip" "e:\vc\xcc\xcc mix editor\release\" "e:\vc\xcc\data\"
wzzip -f "e:\xhp\utilities\XCC_Mixer.zip" "e:\vc\xcc\xcc mixer\release\" "e:\vc\xcc\data\"
wzzip -f "e:\xhp\utilities\XCC_Mod_CL.zip" "e:\vc\xcc\xcc mod creator\release\" "e:\vc\xcc\data\"
wzzip -f "e:\xhp\utilities\XCC_Mod_CL.zip" "e:\vc\xcc\xcc mod launcher\release\"
wzzip -f "e:\xhp\utilities\XCC_Utilities.zip" "e:\vc\xcc\xcc av player\release\" "e:\vc\xcc\data\"
wzzip -f "e:\xhp\utilities\XCC_Utilities.zip" "e:\vc\xcc\xcc mix editor\release\"
wzzip -f "e:\xhp\utilities\XCC_Utilities.zip" "e:\vc\xcc\xcc mixer\release\"
wzzip -f "e:\xhp\utilities\XCC_Utilities.zip" "e:\vc\xcc\xcc universal container reader\release\"
wzzip -f "e:\xhp\utilities\XCC_Utilities.zip" "e:\vc\xcc\xcc tmp editor\release\"
wzzip -f "e:\xhp\utilities\XGS.zip" "e:\vc\xcc\xcc game spy\release\"
wzzip -f "e:\xhp\utilities\XGS.zip" "e:\vc\xcc\xcc game spy player\release\"
wzzip -f "e:\xhp\utilities\XRG_Mod_Launcher.zip" "e:\vc\xcc\xrg mod launcher\release\"
wzzip -f "e:\xhp\utilities\XRG_WOL_Game_Viewer.zip" "e:\vc\xcc\XRG WOL Game Viewer\release\"
wzzip -f "e:\xhp\utilities\XIF_Editor.zip" "e:\vc\xif editor\release\"
wzzip -f "e:\xhp\utilities\XRC.zip" "e:\vc\xcc\xcc ra2 radar customizer\release\" "e:\vc\xcc\data\"
wzzip -f "e:\xhp\utilities\XRMU.zip" "e:\vc\xcc\xcc ra2 map updater\release\" "e:\vc\xcc\data\"
wzzip -f "e:\xhp\utilities\XSE_CLT.zip" "e:\vc\xcc\xse clt\release\" "e:\vc\xcc\data\"
wzzip -f "e:\xhp\utilities\XUCR.zip" "e:\vc\xcc\xcc universal container reader\release\"