//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by XCC Editor.rc
//
#define IDC_SELECT                      3
#define ID_INDICATOR_CELL               101
#define CG_IDR_POPUP_XCCEDITOR_VIEW     102
#define ID_INDICATOR_TEMPLATE           103
#define ID_INDICATOR_STRUCTURE          104
#define CG_IDR_POPUP_CTEMPLATE_SELECTION 105
#define CG_IDD_PROPERTYBAR              106
#define CG_ID_VIEW_PROPERTYBAR          107
#define IDR_MAINFRAME                   128
#define IDR_CCLVLTYPE                   129
#define IDD_OPEN_FROM_MIX_DLG           131
#define IDD_EDIT_STRUCTURES_DLG         133
#define IDD_EDIT_UNITS_DLG              134
#define IDD_EDIT_INFANTRY_DLG           135
#define IDD_EDIT_WAYPOINTS_DLG          137
#define IDD_EDIT_TRIGGERS_DLG           138
#define IDD_EDIT_TRIGGER_DLG            139
#define IDD_EDIT_TEAMTYPES_DLG          142
#define IDD_EDIT_TEAMTYPE_DLG           143
#define IDD_EDIT_BASIC_DLG              144
#define IDD_EDIT_MAP_DLG                145
#define IDD_EDIT_SIDE_DLG               146
#define IDD_INFANTRY_PROPERTIES         149
#define IDD_INFANTRY_PROPERTIES_DLG     150
#define IDD_STRUCTURE_PROPERTIES_DLG    151
#define IDD_UNIT_PROPERTIES_DLG         152
#define IDD_DIALOG1                     153
#define IDD_XCCDIRECTORIES              154
#define IDD_ENERGY_STATUS_DLG           155
#define IDD_EDIT_BRIEFING_DLG           156
#define IDC_LIST1                       1000
#define IDC_LIST2                       1001
#define IDC_NEW_BUTTON                  1002
#define IDC_LIST3                       1002
#define IDC_ACTION_LIST                 1002
#define IDC_EDIT_LONG_NAME              1004
#define IDC_EDIT_SHORT_NAME             1005
#define IDC_EDIT_FLAGS                  1006
#define IDC_EDIT_SIZE                   1007
#define IDC_EDIT_BASE_OX                1008
#define IDC_EDIT_OX                     1008
#define IDC_EDIT_BASE_OY                1009
#define IDC_EDIT_OY                     1009
#define IDC_CHECK_ICON                  1010
#define IDC_CHECK_CIVILIAN              1011
#define IDC_EDIT_C_ROTATIONS            1011
#define IDC_CHECK_BIB                   1012
#define IDC_CHECK_TOP                   1012
#define IDC_CHECK_DESERT                1013
#define IDC_CHECK_TEMPERATE             1014
#define IDC_CHECK_WINTER                1015
#define IDC_CHECK_BLOCKED0              1017
#define IDC_CHECK_BLOCKED1              1018
#define IDC_CHECK_BLOCKED2              1019
#define IDC_DELETE                      1019
#define IDC_CHECK_BLOCKED3              1020
#define IDC_CHECK_BLOCKED4              1021
#define IDC_NEW                         1021
#define IDC_CHECK_BLOCKED5              1022
#define IDC_EDIT                        1022
#define IDC_CHECK_BLOCKED6              1023
#define IDC_COMBO1                      1023
#define IDC_COMBO_CAUSE                 1023
#define IDC_OBJECT_COMBO                1023
#define IDC_COMBO_PLAYER                1023
#define IDC_COMBO_THEATER               1023
#define IDC_COMBO_EDGE                  1023
#define IDC_CHECK_BLOCKED7              1024
#define IDC_COMBO2                      1024
#define IDC_COMBO_EVENT                 1024
#define IDC_ACTION_COMBO                1024
#define IDC_COMBO_ACTION                1024
#define IDC_CHECK_BLOCKED8              1025
#define IDC_COMBO3                      1025
#define IDC_EDIT1                       1025
#define IDC_EDIT_COUNT                  1025
#define IDC_EDIT_ACTION_C               1025
#define IDC_ACTION_EDIT                 1025
#define IDC_EDIT_ACTION                 1025
#define IDC_EDIT_X                      1025
#define IDC_EDIT_CREDITS                1025
#define IDC_EDIT_TYPE                   1025
#define IDC_EDIT_GOODGUY_IN             1025
#define IDC_CHECK_BLOCKED9              1026
#define IDC_COMBO4                      1026
#define IDC_COMBO_SIDE                  1026
#define IDC_EDIT3                       1026
#define IDC_EDIT_BRIEF                  1026
#define IDC_EDIT_Y                      1026
#define IDC_EDIT_BADGUY_IN              1026
#define IDC_CHECK_BLOCKED10             1027
#define IDC_COMBO5                      1027
#define IDC_EDIT2                       1027
#define IDC_EDIT_TEAMTYPE               1027
#define IDC_EDIT_OBJECT_C               1027
#define IDC_OBJECT_EDIT                 1027
#define IDC_EDIT_BUILDLEVEL             1027
#define IDC_EDIT_CX                     1027
#define IDC_EDIT_ANGLE                  1027
#define IDC_EDIT_NEUTRAL_IN             1027
#define IDC_CHECK_BLOCKED11             1028
#define IDC_COMBO6                      1028
#define IDC_COMBO_LOOP                  1028
#define IDC_EDIT5                       1028
#define IDC_EDIT_CARRY_OVER_MONEY       1028
#define IDC_EDIT_CY                     1028
#define IDC_EDIT_CELL                   1028
#define IDC_EDIT_SPECIAL_IN             1028
#define IDC_EDIT6                       1029
#define IDC_EDIT_INTRO                  1029
#define IDC_EDIT_HEALTH                 1029
#define IDC_EDIT_MULTI1_IN              1029
#define IDC_LIST                        1030
#define IDC_EDIT_U1                     1030
#define IDC_EDIT7                       1030
#define IDC_EDIT_LOSE                   1030
#define IDC_EDIT_TRIGGER                1030
#define IDC_EDIT_                       1030
#define IDC_EDIT_GOODGUY_OUT            1030
#define IDC_CHECK_LINK                  1031
#define IDC_EDIT8                       1031
#define IDC_EDITNAME                    1031
#define IDC_EDIT_2                      1031
#define IDC_EDIT_BADGUY_OUT             1031
#define IDC_CHECK_FORCE_MOVE            1032
#define IDC_EDIT9                       1032
#define IDC_EDIT_PERCENT                1032
#define IDC_EDIT_3                      1032
#define IDC_EDIT_NEUTRAL_OUT            1032
#define IDC_CHECK_AUTOCREATE            1033
#define IDC_EDIT10                      1033
#define IDC_EDIT_THEME                  1033
#define IDC_EDIT_4                      1033
#define IDC_EDIT_SPECIAL_OUT            1033
#define IDC_CHECK_REPLACE               1034
#define IDC_EDIT11                      1034
#define IDC_EDIT_WIN                    1034
#define IDC_EDIT_5                      1034
#define IDC_EDIT_MULTI1_OUT             1034
#define IDC_CHECK_FORCE_CREATION        1035
#define IDC_EDIT_MULTI2_IN              1035
#define IDC_EDIT_C_TEAMS                1036
#define IDC_EDIT_MULTI3_IN              1036
#define IDC_OBJECT_INSERT               1037
#define IDC_EDIT_MULTI4_IN              1037
#define IDC_OBJECT_DELETE               1038
#define IDC_EDIT_MULTI5_IN              1038
#define IDC_ACTION_INSERT               1039
#define IDC_EDIT_MULTI6_IN              1039
#define IDC_ACTION_DELETE               1040
#define IDC_EDIT_6                      1040
#define IDC_EDIT_MULTI2_OUT             1040
#define IDC_OBJECT_LIST                 1041
#define IDC_EDIT_7                      1041
#define IDC_EDIT_MULTI3_OUT             1041
#define IDC_EDIT_8                      1042
#define IDC_EDIT_MULTI4_OUT             1042
#define IDC_ACTION_SELECT               1043
#define IDC_CHECK_GOODGUY               1043
#define IDC_EDIT_9                      1043
#define IDC_EDIT_MULTI5_OUT             1043
#define IDC_CHECK_BADGUY                1044
#define IDC_EDIT_10                     1044
#define IDC_EDIT_MULTI6_OUT             1044
#define IDC_CHECKNEUTRAL                1045
#define IDC_CHECK_NEUTRAL               1045
#define IDC_CHECK_SPECIAL               1050
#define IDC_CHECK_MULTI1                1051
#define IDC_CHECK_MULTI2                1052
#define IDC_CHECK_MULTI3                1053
#define IDC_CHECK_MULTI4                1054
#define IDC_CHECK_MULTI5                1055
#define IDC_CHECK_MULTI6                1056
#define IDC_EDIT_NAME                   1057
#define IDC_CHECK_START                 1061
#define IDC_EDIT_PRIMARY                1070
#define IDC_EDIT_SECONDARY              1071
#define IDC_EDIT_CD                     1072
#define IDC_EDIT_DATA                   1073
#define IDC_EDIT4                       1079
#define IDC_BUILD_DT                    1080
#define IDC_CHECK1                      1081
#define IDC_CHECK_XCC_LEVEL             1081
#define ID_FILE_OPEN_FROM_MIX           32771
#define ID_SWITCH_MOVEABLE              32772
#define ID_VIEW_MOVEABLE_FILTER         32774
#define ID_FILE_SAVE_AS_IMAGE           32775
#define ID_VIEW_OVERLAY_LAYER           32777
#define ID_VIEW_TERRAIN_LAYER           32778
#define ID_EDIT_STRUCTURES              32779
#define ID_EDIT_UNITS                   32780
#define ID_EDIT_INFANTRY                32781
#define ID_VIEW_UPDATE                  32783
#define ID_VIEW_BORDER_FILTER           32784
#define ID_VIEW_STRUCTURE_BLOCKED_FILTER 32785
#define ID_POPUP_INFANTRY               32786
#define ID_POPUP_STRUCTURES             32787
#define ID_POPUP_UNITS                  32788
#define ID_POPUP_TEMPLATES              32789
#define ID_POPUP_OVERLAY                32790
#define ID_POPUP_TERRAIN                32791
#define ID_POPUP_DELETE                 32793
#define ID_POPUP_TEMPLATES_ROAD         32794
#define ID_POPUP_TEMPLATES_SHORE        32795
#define ID_POPUP_TEMPLATES_RIDGE        32796
#define ID_POPUP_TEMPLATES_RIVER        32797
#define ID_POPUP_PROPERTIES             32798
#define ID_EDIT_LOCK_TEMPLATE_LAYER     32800
#define ID_EDIT_LOCK_OVERLAY_LAYER      32801
#define ID_EDIT_LOCK_TERRAIN_LAYER      32802
#define ID_EDIT_LOCK_INFANTRY_LAYER     32803
#define ID_EDIT_LOCK_STRUCTURE_LAYER    32804
#define ID_EDIT_LOCK_UNIT_LAYER         32805
#define ID_EDIT_LOCK_SMUDGE_LAYER       32806
#define ID_POPUP_SMUDGE                 32807
#define ID_VIEW_INFANTRY_LAYER          32812
#define ID_VIEW_STRUCTURE_LAYER         32813
#define ID_VIEW_UNIT_LAYER              32814
#define ID_VIEW_SMUDGE_LAYER            32815
#define ID_VIEW_TEMPLATE_LAYER          32816
#define ID_POPUP_STRUCTURES_CIVILIAN    32817
#define ID_VIEW_CELLTRIGGER_LAYER       32818
#define ID_VIEW_WAYPOINT_LAYER          32819
#define ID_POPUP_SET_WAYPOINT           32820
#define ID_EDIT_TRIGGERS                32821
#define ID_EDIT_WAYPOINTS               32822
#define ID_POPUP_SET_CELLTRIGGER        32823
#define ID_EDIT_TEAMTYPES               32824
#define ID_EDIT_BASIC                   32825
#define ID_EDIT_MAP                     32826
#define ID_EDIT_GOODGUY                 32827
#define ID_EDIT_BADGUY                  32828
#define ID_EDIT_SPECIAL                 32829
#define ID_EDIT_NEUTRAL                 32830
#define ID_EDIT_MULTI1                  32831
#define ID_EDIT_MULTI2                  32832
#define ID_EDIT_MULTI3                  32833
#define ID_EDIT_MULTI4                  32834
#define ID_EDIT_MULTI5                  32835
#define ID_EDIT_MULTI6                  32836
#define ID_POPUP_BLOCKED                32837
#define ID_POPUP_FILL_WITH_TIBERIUM     32838
#define ID_POPUP_FILL_WITH_WATER        32839
#define ID_POPUP_FILL_WITH_CELLTRIGGERS 32840
#define ID_POPUP_CLEAR_TEMPLATE_LAYER   32841
#define ID_POPUP_CLEAR_OVERLAY_LAYER    32842
#define ID_POPUP_CLEAR_SMUDGE_LAYER     32843
#define ID_POPUP_CLEAR_TERRAIN_LAYER    32844
#define ID_POPUP_CLEAR_INFANTRY_LAYER   32845
#define ID_POPUP_CLEAR_STRUCTURE_LAYER  32846
#define ID_POPUP_CLEAR_UNIT_LAYER       32847
#define ID_POPUP_CLEAR_CELLTRIGGER_LAYER 32848
#define ID_POPUP_CLEAR_WAYPOINT_LAYER   32849
#define ID_POPUP_FILL_WITH_SANDBAG_WALL 32850
#define ID_POPUP_FILL_WITH_CONCRETE_WALL 32851
#define ID_POPUP_FILL_WITH_CHAIN_LINK_FENCE 32852
#define ID_TOOLS_SET_DIRECTORIES        32856
#define ID_TOOLS_ENERGY_STATUS          32857
#define ID_EDIT_BRIEFING                32858
#define ID_TOOLS_UPGRADE_TIBERIUM       32859

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32860
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
